### ISSUE TITLE
Literature Research

### ISSUE THREAD

**Issue by adriana-madi** [IBP-21-22/intbioproj#2]
Hello everybody!
After the meeting today with Professor Harvey and Bert, we have all agreed to continue with our initial plan and read 2 papers each to be presented to each other Journal Club style on Monday.

Please comment with the Title & link in the thread of this issue, which you can edit at any time. Like this we can keep track of the papers we have read so far to be referenced later when writing our own paper.

**Comment by VasLem** [comment]
The latest Nature Review on AD Amyloid Beta Pathway
https://www.nature.com/articles/s41380-021-01249-0

I will not be presenting this, as I have already gone through most  of it, and I consider as a good-to-know material for the whole team. The most useful sections to go through are:
- Early History of the Amyloid-β Pathway in AD
- Genetic Evidence of the Role of the Aβ Pathway
- Aβ Biochemical Properties from Monomers through Higher Aggregation States, Including Plaques
- The Toxicity of the Aβ Pathway

**Comment by DadaAb** [comment]
Lu, M., Williamson, N., Mishra, A., Michel, C. H., Kaminski, C. F., Tunnacliffe, A., & Schierle, G. S. K. (2019). _Structural progression of amyloid-β Arctic mutant aggregation in cells revealed by multiparametric imaging._ Journal of Biological Chemistry, 294(5), 1478-1487.
https://www.sciencedirect.com/science/article/pii/S0021925820364589

Damotte, V., van der Lee, S. J., Chouraki, V., Grenier‐Boley, B., Simino, J., Adams, H., ... & van Duijn, C. M. (2021). _Plasma amyloid β levels are driven by genetic variants near APOE, BACE1, APP, PSEN2: A genome‐wide association study in over 12,000 non‐demented participants._ Alzheimer's & Dementia.
https://alz-journals.onlinelibrary.wiley.com/doi/10.1002/alz.12333

Presentation:
[2021_12_10.pptx](https://github.com/VasLem/addalova_bip/files/7329289/2021_12_10.pptx)
:

**Comment by VasLem** [comment]
P. Rana, P. Bose, A. Vaidya, V. Rangachari and P. Ghosh, *"Global fitting and parameter identifiability for amyloid-β aggregation with competing pathways"* 2020 IEEE 20th International Conference on Bioinformatics and Bioengineering (BIBE), 2020, pp. 73-78, doi: 10.1109/BIBE50027.2020.00020.
https://ieeexplore.ieee.org/document/9288112
[Global fitting and parameter identifiability for amyloid-β aggregation with competing pathwayspptx.zip](https://github.com/VasLem/addalova_bip/files/7325949/Global.fitting.and.parameter.identifiability.for.amyloid-.aggregation.with.competing.pathwayspptx.zip)

Sorrentino, V., Romani, M., Mouchiroud, L. et al. *Enhancing mitochondrial proteostasis reduces amyloid-β proteotoxicity*. Nature 552, 187–193 (2017).
https://www.nature.com/articles/nature25143
[Enhancing mitochondrial proteostasis reduces amyloid.zip](https://github.com/VasLem/addalova_bip/files/7325856/Enhancing.mitochondrial.proteostasis.reduces.amyloid.zip)

If I got time I am going to read the paper about Aducanumab, the first FDA early access approved drug on Alzheimer (since last June)
https://www.nature.com/articles/nature19323

**Comment by adriana-madi** [comment]
[1] Chen, Gf., Xu, Th., Yan, Y. et al. Amyloid beta: structure, biology and structure-based therapeutic development. Acta Pharmacol Sin 38, 1205–1235 (2017). https://doi.org/10.1038/aps.2017.28
https://www.nature.com/articles/aps201728

[2] https://www.frontiersin.org/articles/10.3389/fnmol.2020.609073/full

**Comment by LoreVanSantvliet** [comment]
[1] Li, D., Liu, C. Hierarchical chemical determination of amyloid polymorphs in neurodegenerative disease. Nat Chem Biol 17, 237–245 (2021). https://doi.org/10.1038/s41589-020-00708-z

[2] R. Gallardo, N. A. Ranson, and S. E. Radford, "Amyloid structures: much more than just a cross-β fold," _Curr. Opin. Struct. Biol., vol. 60, pp. 7-16, 2020, doi: https://doi.org/10.1016/j.sbi.2019.09.001

Presentation:
[20121012_project.pptx](https://github.com/VasLem/addalova_bip/files/7330094/20121012_project.pptx)

Presentation Harvey:
[20211014_project.pptx](https://github.com/VasLem/addalova_bip/files/7330857/20211014_project.pptx)
