### ISSUE TITLE
Terminator presentation 18/10

### ISSUE THREAD

**Issue by LoreVanSantvliet** [IBP-21-22/intbioproj#4]

**Comment by LoreVanSantvliet** [comment]
This is the presentation with a partial literature study (I only read 1 of the papers that were provided), and a proposal for the solution design and project planning. Some key points that still need to happen:
- Read the other paper and include this in the literature study.
- Complete the literature study with additional material if needed.
- Think about extra possibilities for sequence-/function-based features that you would like to include. If you figure out a new one, also start thinking about sources! I for example added k-mer frequencies as sequence-based feature, for which the source is obviously the 3'-UTR itself. I also added subcellular localization as a function-based feature, but I don't know where we could find the subcellular localization for all gene products of yeast, and if I cannot figure this out, we probably better remove it. Also, I don't know if it fits 100% under function-based features (at least more than under sequence-based).
- Think about possible ML techniques we want to use. We should probably try out a bunch of them and see which works out best, but I think questions will be asked about this and we better already have some idea of which ones we want to try.
- Have a look at the planning. Is it okay to group the stuff we want to finish per meeting we have with the whole bioinformatics group, or should we go into more detail (for example, per week)? I'm personally a fan of the former, and I don't think we will have problems with procrastination etc. ( but I can only speak for myself here ofcourse :) )

Just to give you an idea of how much still needs to be added, I timed the presentation the way it is now and I think we would need ±7min for this. So 3-5 extra minutes need to be added. But of course, a lot could still be changed/removed/... from this first version :) 

If needed, I can still work on this presentation tomorrow evening, or saturday morning. Please let me know if there are still things you want me to do on those moments. After then, I'll probably only have time to check now and then to see your progress. 

Btw, I added comments in the powerpoint that indicate what can be said during the presentation.

[20121014_presentation_terminators.pptx](https://github.com/VasLem/addalova_bip/files/7349678/20121014_presentation_terminators.pptx)

**Comment by DadaAb** [comment]
@LoreVanSantvliet
A possible source of subcellular localisation information - https://yplp.yeastgenome.org/ (image based), http://www.weizmann.ac.il/molgen/loqate/ (image and text).

Another metrics I'm thinking of could be like regulons or TFs associated with the corresponding genes, but here the source for this would probably be ... well, non-existent. I'll check. 🤔

**Comment by LoreVanSantvliet** [comment]
I just realized that "cellular component" is one of the 3 existing gene ontology categories, so the subcellular localization is already covered there.

TFs associated to genes in yeast can be found here, I think: http://www.yeastract.com/index.php

**Comment by VasLem** [comment]
After having read the second paper, I found that it contained only one relevant paragraph to our project. In this paragraph, the authors mention that they assessed the expression of mRNAs with the following pattern (ORF)>(GFP)>(X), with X being either a specific heterologous terminator or the endogenous terminator for around 5230 cases, slightly fewer than the ones reported by the first paper, but with fluorescent proteins that displayed better overall efficiency, and in a more controlled environment, as they created their own template-based technique to ligate to c-terminal for high-throughput performance. 

We could surely make use of that database, but I do not know in which degree we could compare it with the first paper case, where there are many differences, notably that the ORF is not being included in the first case, different PCR methods used, and different fluorescent proteins are also in use. A basic approach would be, instead of trying to merge them, use them as distinct responses.  

Given that the response is continuous and there is a certain monotonicity in the intensities relation, we could combine those distinct intensities using a specific unsupervised step.

PS. the data is provided in the supplementary material of the paper and can be accessed by following [this](https://static-content.springer.com/esm/art%3A10.1038%2Fs41592-018-0045-8/MediaObjects/41592_2018_45_MOESM4_ESM.xlsx)
